README.md, package.json, src/JWT.js
=> uport-jwt -> did-jwt

package.json, src/JWT.js, src/__tests__/JWT-test.js, src/__tests__/__snapshots__/JWT-test.js.snap, yarn.lock
This just avoids normalizing the DID so we can support creation of legacy uPort jwts
=> Support MNIDs in createJWT

docs/reference/index.md, src/JWT.js
=> Align documentation with code function parameters

docs/guides/index.md, src/JWT.ts
also fixes #65
I putted everything into one commit as discussed in #73.
I am not sure whether there is further documentation which should be updated or comments that should be adjusted.
Thanks you very much for your help, @mirceanis
=> feat: add parameter for custom headers to createJWT

src/JWT.ts, src/__tests__/JWT-test.ts, src/__tests__/__snapshots__/JWT-test.ts.snap
Fixes: https://github.com/decentralized-identity/did-jwt/issues/54
=> Add verification for multiple audiences

.circleci/config.yml, .releaserc, package-lock.json, package.json
generate changelog during release and post the proper version to package.json
=> fix(build): generate changelog during release

src/__tests__/JWT-test.ts, src/__tests__/SignerAlgorithm-test.ts, src/__tests__/SimpleSigner-test.ts
some tests were falsely passing
=> fix(test): catch rejected promises in tests

src/index.ts
Forgot to add these exports in my last PR.
FYI, looks like tests are passing but two tests are broken and not being awaited on develop.
=> chore: Export JWS functions

Contributing.md, LICENSE
=> docs: add contribution guideline

README.md
=> docs: update sample code in readme

package.json, src/__tests__/VerifierAlgorithm-test.ts, yarn.lock
did-resolver@2.1.0
elliptic@6.5.3
@babel/runtime@7.11.2
=> fix(deps): upgrade dependencies

src/index.ts
Forgot to export this function in my previous PR.
=> fix: export resolveX25519Encrypters function

src/Digest.ts, src/JWE.ts, src/JWT.ts, src/SignerAlgorithm.ts, src/VerifierAlgorithm.ts, src/__tests__/JWE-test.ts, src/__tests__/JWT-test.ts, src/__tests__/VerifierAlgorithm-test.ts, src/__tests__/didkey-test.ts, src/__tests__/xc20pEncryption-test.ts, src/index.ts, src/signers/EdDSASigner.ts, src/signers/EllipticSigner.ts, src/signers/NaclSigner.ts, src/util.ts, src/xc20pEncryption.ts
fixes #152
I also added some extra tests for different key format combos and reformatted the code.
=> fix: add explicit support for EcdsaSecp256k1RecoveryMethod2020

.circleci/config.yml, .eslintrc.js, package.json, webpack.config.js, yarn.lock
=> fix(deps): update dependencies

src/VerifierAlgorithm.ts, src/__tests__/VerifierAlgorithm.test.ts
This PR adds support for secp256k1 [publicKeyJwk](https://www.w3.org/TR/did-core/#dfn-publickeyjwk).
=> feat: support secp256k1 publicKeyJwk

package.json, src/__tests__/JWT.test.ts, yarn.lock
=> Remove deprecated nacl-did and update test

package.json
make it easier to find the source of this package
=> fix: add repository to package.json

package.json
=> fix: remove `exports` statement from package.json

src/JWT.ts, src/index.ts
=> feat: export JWTOptions and JWTVerifyOptions parameter types

package.json, renovate.json, src/Digest.ts, src/dependency.types.d.ts, src/encryption/JWE.ts, src/encryption/xc20pDir.ts, src/util.ts, yarn.lock
=> fix(deps): downgrade uint8arrays and multiformats
