decentralized-identity/did-jwt

README.md, src/JWT.js, src/__tests__/JWT-test.js
To support the use of DID's for [authenticating the owner of a DID](https://w3c-ccg.github.io/did-spec/#authentication).
=> Supports authentication section of DID doc

src/JWT.js
This is recommended solution for coercing legacy MNID addresses in JWTs to DIDs.  
We can export the function to make migration easier for integrators
To avoid polluting the exports from this library, we can then pass it through as an export of the minor release of `uport-credentials`
```javascript
// in credentials/index.js
import { normalizeDID } from 'did-jwt/lib/JWT'
// ...
export {Credentials, SimpleSigner, Contract, ContractFactory, JWT, normalizeDID } 
```
In particular this will help the TI&M team deal with legacy credentials
=> feat: export normalizeDID function from JWT.js

package-lock.json, package.json
NPM Audit had bad things to say about several dependencies, one of which was a non-dev dependency
Before:
found 32 vulnerabilities (14 low, 10 moderate, 8 high) in 27048 scanned packages
run `npm audit fix` to fix 31 of them.
1 vulnerability requires semver-major dependency updates.
After:
found 0 vulnerabilities
in 26984 scanned packages
=> Fixed up issues raised by npm audit

src/JWT.ts, src/__tests__/JWT-test.ts, src/__tests__/__snapshots__/JWT-test.ts.snap
`did-jwt` currently sets the `iat` attribute to the current timestamp in seconds.  The W3C VC JWT spec has been changed to use the `nbf` attribute instead.  This PR changes all occurrences of `iat` to `nbf` when creating and verifying JWTs.
Tests have been updated to check for the presence of `nbf`.
=> change iat to nbf

src/JWT.ts, src/__tests__/JWT-test.ts, src/__tests__/__snapshots__/JWT-test.ts.snap
This PR reverts the changes to `createJWT` introduced in https://github.com/uport-project/did-jwt/pull/41 and slightly alters the behavior of how some of the arguments are used:
- `createJWT` no longer attempts sets the `nbf` attribute to the current timestamp by default
- `createJWT` once again sets the `iat` attribute to the current timestamp by default
- `createJWT` omits the `iat` attribute if it is passed in as `undefined` in the `payload`
- `createJWT` only calculates the `exp` value given the `expiresIn` option if `nbf` is present in the `payload`
`nbf` no longer defaults to the current timestamp is because it's an optional attribute for JWTs, and therefore does not justify causing a breaking change in this library.  `did-jwt-vc` will provide higher level functions for creating …
=> Set `iat` timestamp by default instead of `nbf`

src/JWT.ts, src/__tests__/JWT-test.ts, src/__tests__/__snapshots__/JWT-test.ts.snap
This PR adds support for checking the current time against the `nbf` field when verifying a JWT.  It prioritizes the presence of `nbf` in order to comply with W3C VC standards, but falls back to `iat` when it is absent in order to maintain support for legacy format JWTs.
This completes [#167881436](https://www.pivotaltracker.com/n/projects/2198688/stories/167881436) on pivotal
Test scenarios have been added to validate the behavior for all combinations of `nbf` and `iat` fields being part of the JWT or not.
=> feat: verifyJWT against nbf if present but use iat if not

.circleci/config.yml, .releaserc, src/JWT.ts, src/__tests__/JWT-test.ts, src/__tests__/__snapshots__/JWT-test.ts.snap
This PR releases the changes to support using the `nbf` field to represent the beginning of the JWTs validity period.  JWTs created before this change that use `iat` will still be supported as well.
=> release: add support for nbf attribute

package-lock.json, package.json, src/JWT.ts, src/__tests__/JWT-test.ts
BREAKING CHANGE: verifyJWT now requires the user to provide a did-resolver. This allows the user to configure their own resolver instead of being limited to default ethr-did and https-did resolvers
=> feat: require resolver to be passed as a parameter to verifyJWT

.circleci/config.yml
semantic release error in circle: `[semantic-release]: node version >=10.13 is required. Found v8.16.2.`
=> ci: update node version

.gitignore, package.json, src/VerifierAlgorithm.ts, src/__tests__/JWT-test.ts, src/__tests__/VerifierAlgorithm-test.ts, src/__tests__/__snapshots__/JWT-test.ts.snap
Default ethr-did documents don't define full `publicKeyHex` key material, only `ethereumAddress`, therefore it's not possible to execute `ecVerify` to check for signatures.
This patch introduces a verification mechanism that defaults to `ecRecover` + string match on `ethereumAddress` in case there is no suitable `publicKeyHex` that can pass verification.
This fixes #14 
This fixes #39
=> [Bugfix] ES256K vs ES256K-R algorithm handling

package.json, src/JWT.ts, src/__tests__/JWT-test.ts
This PR add support to create and verify plain JWS. It adds two new functions `createJWS` which is now used by the `createJWT` function, and `verifyJWS` which is **not** used by `verifyJWT` (not much overlap).
In addition I also made some small enhancements:
* Updated the test script to not automatically update the snapshots
* Made the signature verification error messages more informative by adding the token that was failed to verify
=> feat: add methods for creating and verifying JWS

.prettierrc, package.json, src/Digest.ts, src/JWT.ts, src/SignerAlgorithm.ts, src/VerifierAlgorithm.ts, src/__tests__/JWT-test.ts, src/__tests__/NaclSigner-test.ts, src/__tests__/SignerAlgorithm-test.ts, src/__tests__/VerifierAlgorithm-test.ts, src/index.ts
Grouped `options.audience` and `options.callbackUrl` from `verifyJWT` into a single check while allowing for tokens with multiple audience entries.
This reduces the info leaked through errors as well.
Also, ran a reformat on the codebase to align style.
=> refactor: simplify audience checks

src/SimpleSigner.ts, src/__tests__/SimpleSigner-test.ts, src/__tests__/__snapshots__/SimpleSigner-test.ts.snap
It is common to use 0x as a prefix in hex strings, some libs return private keys with that prefix, but SimpleSigner doesn't handle them.
For example ethers.js HDNode returns a hex string with 0x. It took some time to notice why my signed JWT wasn't valid: `Error: Signature invalid for JWT`.
=> fix: handle SimpleSigner privateKey 0x hex prefix by stripping it

src/JWT.ts
Avoid decoding jws twice in verification
=> Refactor JWT.ts

src/EllipticSigner.ts, src/SignerAlgorithm.ts, src/__tests__/EllipticSigner-test.ts, src/__tests__/SignerAlgorithm-test.ts, src/__tests__/__snapshots__/EllipticSigner-test.ts.snap, src/index.ts, src/util.ts
This PR adds a new signer `EllipticSinger` which is similar to `SimpleSigner` but returns a string instead of a signature object. It also adds support for string signatures in `SignerAlgorithms` when using `ES256K`.
Replaces #90
=> feat: add EllipticSigner that returns string

src/JWT.ts
Some of them may be useful in other libs like `uport-credentials` or `did-jwt-vc`.
=> export more JWT interfaces

src/JWT.ts, src/VerifierAlgorithm.ts, src/__tests__/JWT-test.ts, src/index.ts
This expands upon the work done in #121
Some of the interfaces are now publicly exported by this module.
=> fix: export interfaces used for JWT verification

renovate.json
This should reduce some of the noise created by `renovate` bot when updating dependencies
=> ci: group automated dependency updates together

package.json, src/JWT.ts, src/__tests__/JWT-test.ts, src/__tests__/__snapshots__/JWT-test.ts.snap
This PR enables a caller of `createJWS` to pass an `base64url` encoded payload directly. This is useful when you need to sign something that isn't a JSON object.
=> feat: enable detached payloads for JWS

package.json, src/NaclSigner.ts, src/VerifierAlgorithm.ts, yarn.lock
This PR replaces `tweetnacl` with `@stablelib/ed25519` which will reduce the package size. Still keeping `tweetnacl` as a devDep as it's used in a few tests.
=> chore: reduce package size by not using tweetnacl

src/SignerAlgorithm.ts, src/VerifierAlgorithm.ts, src/__tests__/SignerAlgorithm-test.ts, src/__tests__/VerifierAlgorithm-test.ts
Fixes #130 
I've left the old algorithm parameters in for backwards compatibility. I don't know if this is desirable?
=> fix: use EdDSA as the 'alg' header for Ed25519 signatures

src/JWT.ts, src/__tests__/JWT-test.ts
This PR adds a new field called `skewTime` to `JWTVerifyOptions`. If it is present, it will be used to add/remove from `now` when performing timestamp validations when validating JWTs.
Closes #136
=> feat(jwt): add skewTime option that replaces NBF_SKEW if present

src/JWT.ts, src/__tests__/JWT-test.ts, src/__tests__/didkey-test.ts
This fixes #141
All the core pieces were there, but there was a mismatch between the declared supported types and the actual supported types.
=> fix(verifyJWT): fix verification of JWT using EdDSA alg

.vscode/launch.json, package.json, src/JWT.ts, src/__tests__/JWT-test.ts, yarn.lock
According to the did-core spec the `authentication` entries in a DID document can be either key ID `string` references or embedded `PublicKey` objects.
This PR adds support for that as well as preserving backwards compatibility with the `Authentication` data type used previously by some DID methods.
=> feat(did auth): update resolution of authentication entries in DIDDocument

package.json, src/JWT.ts, src/VerifierAlgorithm.ts, src/__tests__/JWT-test.ts, src/__tests__/didkey-test.ts, src/__tests__/xc20pEncryption-test.ts, src/index.ts, src/xc20pEncryption.ts, yarn.lock
Replaces #150 
Fixes #144 
Edit:
I think this would be seen as a breaking release so I flagged it as such.
=> feat!: Upgrade did-resolver to v3

src/JWT.ts, src/__tests__/JWT.test.ts, src/__tests__/didkey.test.ts, src/xc20pEncryption.ts
fixes #158
fixes https://github.com/decentralized-identity/did-jwt-vc/pull/68
=> fix: simplify expected Resolver type in verify methods

package.json, src/JWT.ts, src/__tests__/JWT.test.ts, src/__tests__/__snapshots__/JWT.test.ts.snap, yarn.lock
When creating the segments of a JWT, regular `JSON.stringify()` was being used. Because the ordering is not guaranteed with JSON.stringify - this makes re-creating the JWT out of a W3C format credential very difficult.
By using [json-stable-stringify](https://www.npmjs.com/package/json-stable-stringify) there can be a guaranteed ordering of the properties, meaning as long as the payload contains exactly the same content, you will always get the same JWT (see added test which fails without these changes)
I have also replaced ncal-did with regular jwt decode in the test - nacl-did is [marked as deprecated](https://github.com/uport-project/nacl-did) and was only used in this one place.
=> Use stable stringify when creating payload segments

src/JWT.ts, src/__tests__/JWT.test.ts, src/__tests__/__snapshots__/JWT.test.ts.snap
Fixes https://github.com/decentralized-identity/did-jwt/issues/171
=> fix: don't run JSON.stringify on canonicalized data

src/Digest.ts, src/JWE.ts, src/__tests__/JWE.test.ts, src/__tests__/didkey.test.ts, src/__tests__/jwe-vectors.js, src/index.ts, src/xc20pEncryption.ts
Added ECDH-1PU+XC20PKW, AuthEncrypter/Decrypter and AnonEncrypter/Decrypter
=> Added support for authenticated encryption

.github/workflows/release.yml, .github/workflows/test.yml
A maintenance PR that enables the use of github actions for building / testing / releasing.
This is a prerequisite to removing the dependency on circleci.
The results of this PR are already visible in the `Build and Test NODE / build-test (pull_request)` status check which runs the `.github/workflows/test.yml` workflow
=> chore(ci): add github workflows

.eslintrc.js, .github/stale.yml, package.json, renovate.json, src/JWE.ts, src/JWT.ts, src/SignerAlgorithm.ts, src/VerifierAlgorithm.ts, src/__tests__/JWE.test.ts, src/__tests__/didkey.test.ts, src/signers/ES256KSigner.ts, src/util.ts, src/xc20pEncryption.ts, tsconfig.json, yarn.lock
* adjust some parameters of the build to produce non-minified outputs.
* fixes #173
* enable strict mode and eslint
* fixes #174
* added more explicit types to reduce ambiguity and remove all compiler and linter linter warnings
* adjust bot schedule for less dependency update noise
=> fix(build): non-minified outputs and better handling of strict mode

src/JWT.ts
=> fix: remove `type` from `JWTPayload`

src/ECDH.ts, src/__tests__/JWE.test.ts, src/__tests__/xc20pEncryption.test.ts, src/index.ts, src/xc20pEncryption.ts
With this change, users will be able to use the JWE functionality even without direct access to sender or recipient `secretKey` material, as long as they can provide a wrapper method that resolves to the shared secret.
This also adds a `createX25519ECDH(mySecretKey: Uint8Array): ECDH` method that creates such a wrapper from an existing key.
The signature of the wrapper is this:
```typescript
type ECDH = (theirPublicKey: Uint8Array) => Promise<Uint8Array>
```
fixes #183
=> feat: enable remote ECDH for JWE [de]encrypters

src/__tests__/JWE.test.ts, src/__tests__/jwe-vectors.js, src/xc20pEncryption.ts
skid is no longer (was meant to be encrypted to recipient) in the recipient header and only added to the protected header.
=> fix: removed skid from the recipient header

src/__tests__/xc20pEncryption.test.ts, src/xc20pEncryption.ts
Solves https://github.com/decentralized-identity/did-jwt/issues/202
Provides two additional test cases:
- did's controller has key agreement keys
- did is controlled by another did of the same type, and the grandparent controller has key agreement keys
cc @oed
=> feat: add recursive lookup for key exchange keys when encrypting data

src/blockchains/bip122.ts, src/blockchains/index.ts
A Bitcoin address in Base58Check encoding has a version byte prefix that indicates the type or use of the address. Bitcoin mainnet uses a zero byte, but test networks and forks or alternative networks typically use different version bytes.
Here are a few values of version bytes for addresses:
Hex  |   Network        | Reference
-------|------------------|--------------------
`0x00` | Bitcoin          | https://github.com/bitcoin/bitcoin/blob/fe03f7a37fd0ef05149161f6b95a25493e1fe38f/src/chainparams.cpp#L131
`0x6f` | Bitcoin test     | https://github.com/bitcoin/bitcoin/blob/fe03f7a37fd0ef05149161f6b95a25493e1fe38f/src/chainparams.cpp#L238
`0x30` | Litecoin         | https://github.com/litecoin-project/litecoin/blob/fa0cdba24a0818c4a7206f282c86f0eac6767e72/src/chainparams.cpp#L128
`0x0e` | …
=> Allow alternative address prefixes in bip122 blockchain account ids

src/VerifierAlgorithm.ts
This is a quick fix adding missing quotes around `undefined`.
Without the quotes, `typeof blockchainAccountId !== undefined` always return `true`, and all the `authenticators` are added to `blockchainAddressKeys`, which causes the lib to unnecessarily call `signer = verifyRecoverableES256K(data, signature, blockchainAddressKeys)` (line 78) when `signer` is falsy.
=> fix: add missing quotes around undefined

src/JWE.ts, src/__tests__/JWT.test.ts, src/__tests__/util.test.ts, src/xc20pEncryption.ts
Should fix https://github.com/decentralized-identity/did-jwt/issues/216
=> feat: Drop Buffer

src/VerifierAlgorithm.ts, src/__tests__/VerifierAlgorithm.test.ts
This PR adds support for Ed25519 `publicKeyJwk`.
Almost exactly 1 year after https://github.com/decentralized-identity/did-jwt/pull/160 😅
=> feat: support Ed25519 publicKeyJwk

package.json, src/VerifierAlgorithm.ts, src/__tests__/JWT.test.ts, src/blockchains/index.ts, yarn.lock
The fix is a case insensitive comparison of recovered addresses.
I also added a test to check for regressions of this issue.
fixes #231
=> fix: ES256K-R verification with checksumAddress in eip155 blockchainAccountId

src/xc20pEncryption.ts
I'm not sure why but bundlers don't seem to pick this up and translate it, but since it is safe to replace the single use of that operator why not make it easier?
fixes #236
=> fix: remove nullish coalescing operator

src/JWT.ts, src/__tests__/JWT.test.ts
This merge requests introduces a new interface in the JWT.ts module which JWTVerifyPolicies. The policies at the moment are only restricted to timestamps, but can be further expanded upon to serve better. The JWTVerifyPolicies are made a part of VerifyJWTOptions defined as `policies`. These policies are used to be able to override a certain checks that are made in the VerifyJWT command. It is not a breaking change but an extension to the current implementation.
The checks for these policies will not me made only and only if they are explicitly stated to be 
- nbf  (Not Before)
- iat   (Issued At)
- exp (Expires At)
Further tests were added to the JWT.test.ts to check whether the implemented policies were properly allowing the presentation to verify in case of a failure and the policy was …
=> Introduced Policies to override Timestamp checking

README.md, src/Errors.ts, src/JWT.ts, src/__tests__/JWT.test.ts, src/index.ts
fixes #239 
.. without the mentioned breaking change.
Errors are still thrown, but the prefixes for the known failure cases are also exported now as an enum.
=> feat: add `aud` override policy for verification

src/Errors.ts, src/__tests__/ES256Signer.test.ts, src/__tests__/JWT.test.ts
This changes the `JWT_ERROR` collection from an enum to a plain object.
closes #243
Although this is technically a breaking change, not enough time has passed since the introduction of the original enum for it to gain any usage.
=> fix: export error prefixes as object instead of enum

src/JWT.ts
According to [JWT VC Presentation Profile](https://identity.foundation/jwt-vc-presentation-profile/#id-token-validation), the `iss` claim must be `https://self-issued.me/v2/openid-vc` instead of `https://self-issued.me/v2`
=> support jwts generated for JWT VC Presentation Profile

src/JWT.ts, src/__tests__/JWT.test.ts
According to JWT Presentation Profile, the SIOP Request JWT does not contain an `iss` claim, it must have a `client_id` claim instead. See https://identity.foundation/jwt-vc-presentation-profile/#self-issued-op-request-object
=> add support for SIOP request JWT

package.json, src/__tests__/JWT.test.ts, yarn.lock
- this dev dependency was bringing in versions of multiformats / multicodec that may be causing issues in other projects
- it's easiest to just remove this dependency and hardcode the values it was generating, rather than sorting out all dependency issues across multiple repos
=> chore: remove dev dependency did-key-creator

.github/workflows/release.yml, .github/workflows/test.yml
This should make github release workflows run on other branches too, so that we can publish prereleases
=> ci: add more branches for releases

jest.config.mjs, package.json, src/JWE.ts, src/__tests__/JWE.test.ts, src/__tests__/jwe-vectors.ts, src/aesEncryption.ts, src/xc20pEncryption.ts, yarn.lock
This PR adds support for AES key wrapping (required in [didcomm encrypted messaging](https://identity.foundation/didcomm-messaging/spec/#key-wrapping-algorithms)) for X25519 ECDH.
AES key wrapping is implemented using a new dependency, `isomorphic-webcrypto`, for now.
This also includes some options for working with common `epk`/`alg` values between recipients.
Merging this should release a new alpha pre-release
=> initial support for X25519 `ECDH-ES+A256KW` alg JWE

src/__tests__/VerifierAlgorithm.test.ts, src/__tests__/util.test.ts, src/util.ts
=> fix: add padding to bigints whose byte-length is expected

package.json, src/blockchains/cosmos.ts, src/encryption/xc20pDir.ts, yarn.lock
#280 improved dependency situation a lot.
- `bech32` was replaced with audited `@scure/base`
- `@stablelib` was replaced with `@noble/ciphers`
cc @ukstv
=> Replace bech32 and old chacha with noble and scure packages

src/VerifierAlgorithm.ts, src/__tests__/VerifierAlgorithm.test.ts, src/__tests__/didkey.test.ts, src/index.ts, src/util.ts
fixes #297
Some users of `publicKeyMultibase` actually encode a multicodec prefixed byte array.
This leads to keys that are not decoded properly and thus are not usable for verification.
This fix includes some heuristics to try to decode multibase directly if it fits known public key lengths and then attempt multicodec decoding.
This PR also exports the methods used for key conversions for use in other libraries.
=> feat: interpret publicKeyMultibase as multicodec

src/__tests__/EdDSASigner.test.ts, src/signers/EdDSASigner.ts
Only the first 32 bytes are used as the actual key
fixes #289
=> fix: accept 32 or 64 bytes as keys for EdDSASigner

src/ConditionalAlgorithm.ts, src/JWT.ts, src/VerifierAlgorithm.ts, src/__tests__/JWT.test.ts, src/__tests__/VerifierAlgorithm.test.ts, src/__tests__/xc20pEncryption.test.ts, src/encryption/xc20pEncryption.ts, src/index.ts, src/util.ts
fixes #304
This PR adds support for `Multikey` verification methods, both for signature verification and for key agreement.
I also added a few internal mappings for known key types, verification methods, algorithms and multiformat codecs.
BREAKING CHANGE: The return types have changed for  of `extractPublicKeyBytes()` and `multibaseToBytes()` from Uint8Arrays to Objects containing the `keyBytes: Uint8Array` and a decoded or inferred `keyType: string | undefined`
Merging this PR should trigger a major version bump
=> feat: add support for Multikey

.github/workflows/release.yml, .github/workflows/test.yml
This should unblock most of the renovate bot automatic upgrades
=> chore(ci): bump GH action versions

package.json, yarn.lock
This bumps the dependencies to their latest versions, including `multiformats` and `uint8arrays`.
closes #312
BREAKING CHANGE: latest versions of some dependencies may not behave properly in CommonJS projects and bundlers since they only publish pure ESM packages.
=> chore(deps): Update dependencies

src/JWT.ts
This PR adds the caught error to the error message.
Motivation: debugging interoperability issues between platforms.
=> Improve Invalid JWT Error Handling
